# Use the official Node.js image with your desired version as the base image
FROM node:14

# Create a directory to hold the application code inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if present) to the working directory
COPY ./package*.json ./

# Install npm dependencies
RUN npm install

# Expose the port on which your Node.js application will run
EXPOSE 3000

# Command to run your Node.js application
CMD ["node", "server.js"]
